---
# File inspired by official docker-compose.yaml example file (get https://raw.githubusercontent.com/open-wanderer/wanderer/main/docker-compose.yml)
# All available environment variables and descriptions can be found here: https://wanderer.to/run/environment-configuration/

services:
  search:
    container_name: wanderer-search
    image: getmeili/meilisearch:v1.36.0
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environment:
      MEILI_URL: http://search:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    networks:
      - wanderer
    volumes:
      - ./data/meili:/meili_data
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s

  db:
    container_name: wanderer-db
    image: flomp/wanderer-db
    depends_on:
      search:
        condition: service_healthy
    environment:
      ORIGIN: ${ORIGIN}
      PUBLIC_POCKETBASE_URL: http://db:8090
      POCKETBASE_ENCRYPTION_KEY: ${POCKETBASE_ENCRYPTION_KEY}
      MEILI_URL: http://search:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    ports:
      - "8090:8090"
    networks:
      - wanderer
    restart: unless-stopped
    volumes:
      - ./data/pb_data:/pb_data
    healthcheck:
      test: ["CMD", "/curl", "--fail", "http://localhost:8090/health"]
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s

  web:
    container_name: wanderer-web
    image: flomp/wanderer-web
    depends_on:
      search:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      ORIGIN: ${ORIGIN}
      PUBLIC_POCKETBASE_URL: http://db:8090
      PUBLIC_DISABLE_SIGNUP: ${PUBLIC_DISABLE_SIGNUP}
      BODY_SIZE_LIMIT: ${BODY_SIZE_LIMIT}

      UPLOAD_FOLDER: /app/uploads
      # UPLOAD_USER: ${UPLOAD_USER}
      # UPLOAD_PASSWORD: ${UPLOAD_PASSWORD}

      MEILI_URL: http://search:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}

      OVERPASS_API_URL: ${OVERPASS_API_URL}
      VALHALLA_URL: ${VALHALLA_URL}
      PUBLIC_VALHALLA_URL: ${PUBLIC_VALHALLA_URL}
      NOMINATIM_URL: ${NOMINATIM_URL}
    volumes:
      - ./data/uploads:/app/uploads
    ports:
      - "3000:3000"
    networks:
      - wanderer
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://localhost:3000/"]
    #   interval: 15s
    #   retries: 10
    #   start_period: 20s
    #   timeout: 10s
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/"]
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s

networks:
  wanderer:
    driver: bridge